version: "3.8"

services:
  latex:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: latex-ta
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: tail -f /dev/null
    stdin_open: true
    tty: true
